export const fontOptions = [
  { label: "Arial", value: "Arial, sans-serif" },
  { label: "Verdana", value: "Verdana, sans-serif" },
  { label: "Georgia", value: "Georgia, serif" },
  { label: "Times New Roman", value: "Times New Roman, serif" },
  { label: "Courier New", value: "Courier New, monospace" },
  { label: "Tahoma", value: "Tahoma, sans-serif" },
  { label: "Helvetica", value: "Helvetica, sans-serif" },
  { label: "Palatino", value: "Palatino, serif" },
  { label: "Garamond", value: "Garamond, serif" },
  { label: "Book Antiqua", value: "Book Antiqua, serif" },
  { label: "Arial Black", value: "Arial Black, sans-serif" },
  { label: "Comic Sans MS", value: "Comic Sans MS, cursive" },
  { label: "Impact", value: "Impact, fantasy" },
  { label: "Lucida Sans Unicode", value: "Lucida Sans Unicode, sans-serif" },
  { label: "Lucida Console", value: "Lucida Console, monospace" },
  { label: "Trebuchet MS", value: "Trebuchet MS, sans-serif" },
  { label: "Geneva", value: "Geneva, sans-serif" },
  { label: "Copperplate", value: "Copperplate, fantasy" },
  { label: "Brush Script MT", value: "Brush Script MT, cursive" },
  { label: "Optima", value: "Optima, sans-serif" },
];
