import { h2styles, pBase, buttonType } from "@/styles/Type";
import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";
import Hero from "@/mainWebsite/hero/Index";
import { Container, MediaQueries } from "@/styles/Utilities";
import Examples from "@/mainWebsite/examples/Index";

const LayoutContainer = styled.nav`
  display: flex;
  justify-content: space-between;
  ${Container}
  /* padding-top: 20px; */
  align-items: center;
`;

const Logo = styled.img`
  width: 200px;
  @media ${MediaQueries.tablet} {
    width: 150px;
  }
`;

const LinkStyled = styled(Link)`
  ${buttonType}
  width: unset;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Timeline That</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LayoutContainer>
          <Logo src="/timeline_that_logo.png" alt="Timeline That Logo" />
          <LinkStyled href="/auth/authenticate">Login or sign up</LinkStyled>
        </LayoutContainer>
        <Hero />
        <Examples />
      </main>
    </>
  );
}
