import { h2styles, pBase } from "@/styles/Type";
import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";

const Logo = styled.h1`
  ${h2styles}
`;

const LinkStyled = styled(Link)`
  ${pBase}
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Timeline That</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Logo>Timeline That</Logo>
        <LinkStyled href="/auth/authenticate">Login or sign up</LinkStyled>
      </main>
    </>
  );
}
